"""Self-healing module — rollback management and drift detection.

Phase 1 (this module):
  - DriftDetector: collects execution metrics (skill success/failure rates,
    identity veto counts, anomaly rates). Metrics are persisted to SQLite
    so they survive process restarts. When a metric crosses a threshold,
    a rollback candidate is generated and queued for human confirmation.
  - RollbackManager: manages rollback candidates. Triggered by DriftDetector
    or by manual flagging. Does NOT execute any rollback without explicit
    human confirmation via the confirm_rollback() method.

Phase 2 (sandbox/, future):
  - Isolated environment for skill mutation and benchmark comparison.
  - No auto-merge: sandbox results inform human decisions, not code changes.
"""

from __future__ import annotations

import aiosqlite
import json
import time
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger(__name__)


# ── Enums ───────────────────────────────────────────────────────────────


class RollbackReason(StrEnum):
    """Why a rollback candidate was generated."""

    CONSECUTIVE_FAILURES = "consecutive_failures"
    MANUAL_FLAG = "manual_flag"
    DRIFT_THRESHOLD = "drift_threshold"


class RollbackStatus(StrEnum):
    """Lifecycle state of a rollback candidate."""

    PENDING = "pending"       # Generated, awaiting human confirmation
    CONFIRMED = "confirmed"   # Human approved — rollback executed
    REJECTED = "rejected"      # Human declined
    EXPIRED = "expired"        # Stale candidate, no longer actionable


class MetricType(StrEnum):
    """Types of drift metrics tracked."""

    SKILL_SUCCESS = "skill_success"
    SKILL_FAILURE = "skill_failure"
    IDENTITY_VETO = "identity_veto"
    ANOMALY_RESPONSE = "anomaly_response"


# ── Data Classes ────────────────────────────────────────────────────────


@dataclass
class RollbackCandidate:
    """A proposed rollback, generated by DriftDetector or manual flag."""

    candidate_id: str
    skill_name: str
    current_version: str
    target_version: str | None  # None means "find previous stable"
    reason: RollbackReason
    detail: str
    status: RollbackStatus = RollbackStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    confirmed_at: datetime | None = None
    confirmed_by: str | None = None


@dataclass
class DriftMetric:
    """A single metric data point."""

    metric_type: MetricType
    skill_name: str | None
    value: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = field(default_factory=dict)


# ── DriftDetector ──────────────────────────────────────────────────────


_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS drift_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric_type TEXT NOT NULL,
    skill_name TEXT,
    value REAL NOT NULL,
    timestamp TEXT NOT NULL,
    metadata TEXT DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_metrics_skill_type
    ON drift_metrics(skill_name, metric_type);

CREATE TABLE IF NOT EXISTS rollback_candidates (
    candidate_id TEXT PRIMARY KEY,
    skill_name TEXT NOT NULL,
    current_version TEXT NOT NULL,
    target_version TEXT,
    reason TEXT NOT NULL,
    detail TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL,
    confirmed_at TEXT,
    confirmed_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_rollback_status
    ON rollback_candidates(status);
"""


class DriftDetector:
    """Detects drift in skill performance and generates rollback candidates.

    Metrics are persisted to SQLite — process restarts do not lose history.
    When consecutive failures exceed the threshold, a rollback candidate is
    generated and queued (status=pending). No automatic rollback execution.
    """

    def __init__(
        self,
        db_path: Path,
        failure_threshold: int = 5,
        window_size: int = 100,
    ) -> None:
        self._db_path = Path(db_path)
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._failure_threshold = failure_threshold
        self._window_size = window_size
        self._conn: aiosqlite.Connection | None = None

    async def _get_conn(self) -> aiosqlite.Connection:
        if self._conn is None:
            self._conn = await aiosqlite.connect(str(self._db_path))
            self._conn.row_factory = aiosqlite.Row
            await self._conn.executescript(_SCHEMA_SQL)
            await self._conn.commit()
            logger.info("drift_detector_initialized", db_path=str(self._db_path))
        return self._conn

    async def record_metric(
        self,
        metric_type: MetricType,
        skill_name: str | None,
        value: float,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Record a metric data point."""
        conn = await self._get_conn()
        await conn.execute(
            "INSERT INTO drift_metrics (metric_type, skill_name, value, timestamp, metadata) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                metric_type.value,
                skill_name,
                value,
                datetime.now(UTC).isoformat(),
                json.dumps(metadata or {}),
            ),
        )
        await conn.commit()

    async def record_skill_execution(
        self,
        skill_name: str,
        success: bool,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Record a skill execution result and check for drift."""
        metric_type = MetricType.SKILL_SUCCESS if success else MetricType.SKILL_FAILURE
        await self.record_metric(metric_type, skill_name, 1.0, metadata)

        if not success:
            await self._check_consecutive_failures(skill_name)

    async def record_identity_veto(
        self,
        rule_name: str,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Record that an identity rule was vetoed/overridden."""
        await self.record_metric(
            MetricType.IDENTITY_VETO, rule_name, 1.0, metadata
        )

    async def record_anomaly(
        self,
        source: str,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Record an anomalous response or behavior."""
        await self.record_metric(
            MetricType.ANOMALY_RESPONSE, source, 1.0, metadata
        )

    async def get_consecutive_successes(self, skill_name: str) -> int:
        """Number of consecutive successful executions of a skill.

        Public API used by the Reflex Layer (harness/reflex.py) to decide
        promotion eligibility. Successes are counted from the most recent
        metric backwards; the run ends at the first failure.
        """
        conn = await self._get_conn()
        cursor = await conn.execute(
            "SELECT metric_type FROM drift_metrics "
            "WHERE skill_name = ? AND metric_type IN ('skill_success', 'skill_failure') "
            "ORDER BY timestamp DESC LIMIT 50",
            (skill_name,),
        )
        rows = await cursor.fetchall()
        cursor.close()

        consecutive = 0
        for row in rows:
            if row["metric_type"] == MetricType.SKILL_SUCCESS.value:
                consecutive += 1
            else:
                break
        return consecutive

    async def _check_consecutive_failures(self, skill_name: str) -> None:
        """Check if consecutive failures exceed the threshold."""
        conn = await self._get_conn()
        cursor = await conn.execute(
            "SELECT metric_type FROM drift_metrics "
            "WHERE skill_name = ? AND metric_type IN ('skill_success', 'skill_failure') "
            "ORDER BY timestamp DESC LIMIT ?",
            (skill_name, self._window_size),
        )
        rows = await cursor.fetchall()
        cursor.close()

        consecutive = 0
        for row in rows:
            if row["metric_type"] == "skill_failure":
                consecutive += 1
            else:
                break

        if consecutive >= self._failure_threshold:
            await self._generate_rollback_candidate(
                skill_name,
                RollbackReason.CONSECUTIVE_FAILURES,
                f"{consecutive} consecutive failures detected "
                f"(threshold={self._failure_threshold})",
            )

    async def _generate_rollback_candidate(
        self,
        skill_name: str,
        reason: RollbackReason,
        detail: str,
        target_version: str | None = None,
        current_version: str = "unknown",
    ) -> str:
        """Generate a rollback candidate and queue it for confirmation.

        Args:
            skill_name: The skill to roll back.
            reason: Why the candidate was generated.
            detail: Human-readable details.
            target_version: Version to roll back to (None = newest STABLE).
            current_version: The version currently active. Callers with a
                SkillStore should pass the real version.
        """
        candidate_id = str(uuid.uuid4())
        conn = await self._get_conn()
        await conn.execute(
            "INSERT INTO rollback_candidates "
            "(candidate_id, skill_name, current_version, target_version, "
            " reason, detail, status, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (
                candidate_id,
                skill_name,
                current_version,
                target_version,
                reason.value,
                detail,
                RollbackStatus.PENDING.value,
                datetime.now(UTC).isoformat(),
            ),
        )
        await conn.commit()
        logger.warning(
            "rollback_candidate_generated",
            candidate_id=candidate_id,
            skill_name=skill_name,
            reason=reason.value,
            detail=detail,
        )
        return candidate_id

    async def get_pending_candidates(self) -> list[dict[str, Any]]:
        """Get all pending rollback candidates."""
        conn = await self._get_conn()
        cursor = await conn.execute(
            "SELECT * FROM rollback_candidates WHERE status = 'pending' "
            "ORDER BY created_at DESC"
        )
        rows = await cursor.fetchall()
        cursor.close()
        return [dict(row) for row in rows]

    async def get_failure_rate(
        self,
        skill_name: str,
        window: int = 50,
    ) -> float:
        """Calculate the failure rate for a skill over the last N executions."""
        conn = await self._get_conn()
        cursor = await conn.execute(
            "SELECT metric_type FROM drift_metrics "
            "WHERE skill_name = ? AND metric_type IN ('skill_success', 'skill_failure') "
            "ORDER BY timestamp DESC LIMIT ?",
            (skill_name, window),
        )
        rows = await cursor.fetchall()
        cursor.close()
        if not rows:
            return 0.0
        failures = sum(1 for r in rows if r["metric_type"] == "skill_failure")
        return failures / len(rows)

    async def close(self) -> None:
        if self._conn is not None:
            await self._conn.close()
            self._conn = None
            logger.info("drift_detector_closed")


# ── RollbackManager ────────────────────────────────────────────────────


class RollbackManager:
    """Manages rollback candidates — never executes without human confirmation.

    The manager:
    1. Lists pending candidates (generated by DriftDetector)
    2. Executes confirmed rollbacks (status=pending → confirmed)
    3. Rejects candidates (status=pending → rejected)

    The actual skill version switch is delegated to SkillStore — this module
    only manages the confirmation workflow.
    """

    def __init__(
        self,
        drift_detector: DriftDetector,
        skill_store: Any | None = None,
    ) -> None:
        self._detector = drift_detector
        self._skill_store = skill_store

    async def list_pending(self) -> list[RollbackCandidate]:
        """List all rollback candidates awaiting confirmation."""
        pending = await self._detector.get_pending_candidates()
        candidates: list[RollbackCandidate] = []
        for row in pending:
            candidates.append(
                RollbackCandidate(
                    candidate_id=row["candidate_id"],
                    skill_name=row["skill_name"],
                    current_version=row["current_version"],
                    target_version=row["target_version"],
                    reason=RollbackReason(row["reason"]),
                    detail=row["detail"],
                    status=RollbackStatus(row["status"]),
                    created_at=datetime.fromisoformat(row["created_at"]),
                )
            )
        return candidates

    async def confirm_rollback(
        self,
        candidate_id: str,
        confirmed_by: str = "human",
    ) -> dict[str, Any]:
        """Execute a rollback after human confirmation.

        Returns a dict with the rollback result. If a SkillStore is
        connected, the skill version is actually rolled back. If not,
        only the candidate status is updated.
        """
        conn = await self._detector._get_conn()
        cursor = await conn.execute(
            "SELECT * FROM rollback_candidates WHERE candidate_id = ? AND status = 'pending'",
            (candidate_id,),
        )
        row = await cursor.fetchone()
        cursor.close()

        if row is None:
            return {
                "status": "error",
                "detail": f"No pending candidate with id={candidate_id}",
            }

        skill_name = row["skill_name"]
        target_version = row["target_version"]

        # Resolve the real current version when the candidate only holds a
        # placeholder (generated without a SkillStore reference).
        current_version = row["current_version"]
        if current_version in ("unknown", "current") and self._skill_store is not None:
            try:
                current_skill = await self._skill_store.get_by_name(skill_name)
                if current_skill is not None:
                    current_version = current_skill.version
            except Exception:
                logger.warning(
                    "current_version_resolve_failed",
                    skill_name=skill_name,
                    exc_info=True,
                )

        # If a SkillStore is connected, perform the actual rollback
        skill_rolled_back = False
        if self._skill_store is not None:
            try:
                skill_rolled_back = await self._skill_store.rollback_to_stable(
                    skill_name, target_version
                )
            except Exception as exc:
                logger.error(
                    "rollback_execution_failed",
                    candidate_id=candidate_id,
                    skill_name=skill_name,
                    error=str(exc),
                )
                return {
                    "status": "error",
                    "detail": f"Rollback execution failed: {exc}",
                }

        # Update candidate status
        await conn.execute(
            "UPDATE rollback_candidates SET status = 'confirmed', "
            "confirmed_at = ?, confirmed_by = ? WHERE candidate_id = ?",
            (datetime.now(UTC).isoformat(), confirmed_by, candidate_id),
        )
        await conn.commit()

        logger.info(
            "rollback_confirmed",
            candidate_id=candidate_id,
            skill_name=skill_name,
            confirmed_by=confirmed_by,
            skill_rolled_back=skill_rolled_back,
        )

        return {
            "status": "confirmed",
            "candidate_id": candidate_id,
            "skill_name": skill_name,
            "current_version": current_version,
            "target_version": target_version,
            "skill_rolled_back": skill_rolled_back,
            "confirmed_by": confirmed_by,
        }

    async def reject_rollback(
        self,
        candidate_id: str,
        reason: str = "",
        rejected_by: str = "human",
    ) -> dict[str, Any]:
        """Reject a rollback candidate."""
        conn = await self._detector._get_conn()
        cursor = await conn.execute(
            "UPDATE rollback_candidates SET status = 'rejected', "
            "confirmed_at = ?, confirmed_by = ? "
            "WHERE candidate_id = ? AND status = 'pending'",
            (
                datetime.now(UTC).isoformat(),
                f"{rejected_by}: {reason}" if reason else rejected_by,
                candidate_id,
            ),
        )
        await conn.commit()
        rowcount = cursor.rowcount
        cursor.close()

        if rowcount == 0:
            return {
                "status": "error",
                "detail": f"No pending candidate with id={candidate_id}",
            }

        logger.info(
            "rollback_rejected",
            candidate_id=candidate_id,
            reason=reason,
            rejected_by=rejected_by,
        )
        return {
            "status": "rejected",
            "candidate_id": candidate_id,
            "reason": reason,
        }

    async def manual_flag(
        self,
        skill_name: str,
        detail: str,
        target_version: str | None = None,
    ) -> str:
        """Manually flag a skill for rollback (bypasses DriftDetector)."""
        return await self._detector._generate_rollback_candidate(
            skill_name,
            RollbackReason.MANUAL_FLAG,
            detail,
            target_version,
        )
