"""LLMEngine — the cognitive compute engine. Pure reasoning, no state.

The LLMEngine is the core cognitive capability of MyHarness. Per P0 and P1,
it is stateless by design:

- No stored conversations
- No identity (identity lives in Memory System)
- No memory of its own (memory lives in Memory System)
- All context comes from ContextBuilder on each call

The engine constructs prompts from Jinja2 templates, calls the LLM provider,
parses JSON responses into structured types (Plan, Reflection, SkillProposal),
and returns them to the caller.

Per P8: The engine supports provider switching at runtime without losing
any state (since it has none to lose).
"""

from __future__ import annotations

import json
import uuid
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

import structlog
from jinja2 import BaseLoader, Environment, StrictUndefined

from myharness.core.exceptions import ProviderError, TokenLimitError
from myharness.llm.context import ContextBuilder
from myharness.llm.interfaces import LLMProvider
from myharness.llm.prompts import (
    COMPILE_SYSTEM_PROMPT,
    IDENTITY_INTERPRETATION_PROMPT,
    IDENTITY_UPDATE_PROPOSAL_PROMPT,
    PLAN_SYSTEM_PROMPT,
    REFLECT_SYSTEM_PROMPT,
    THINK_SYSTEM_PROMPT,
    THINK_USER_PROMPT,
)
from myharness.schema.identity import IdentityField, IdentityUpdateProposal
from myharness.schema.skill import SkillProposal

logger = structlog.get_logger(__name__)

# Jinja2 environment for prompt rendering
_jinja_env = Environment(loader=BaseLoader(), autoescape=False, undefined=StrictUndefined)


# ── Structured Output Types ────────────────────────────────────────────


@dataclass
class PlanStep:
    """A single step in an execution plan."""

    step_id: str
    action: str
    skill_name: str | None
    parameters: dict[str, Any]
    expected_outcome: str


@dataclass
class Plan:
    """A structured execution plan generated by the LLM Engine.

    This is the single plan model for the whole system. The runtime
    interrupt handler and the harness executor both consume it, so a
    second, differently-shaped plan type must not be introduced: the
    executor reads ``step.skill_name`` attributes and silently skips any
    step that is a plain dict.
    """

    plan_id: str
    goal: str
    steps: list[PlanStep]
    reasoning: str
    created_at: datetime
    current_step: int = 0
    """Execution cursor — index of the next step to run. Used to pause and
    resume a plan across interrupts."""


@dataclass
class Reflection:
    """Result of reflecting on an experience."""

    reflection_id: str
    summary: str
    lessons_learned: list[str]
    skill_improvement_suggestions: list[str]
    identity_implications: list[str]
    emotional_tone: str


# ── JSON Response Parsing ──────────────────────────────────────────────


def _extract_json(text: str) -> dict[str, Any]:
    """Extract a JSON object from LLM response text.

    Handles responses wrapped in ```json fences, plain JSON, or
    JSON embedded in other text.

    Args:
        text: Raw LLM response text.

    Returns:
        Parsed JSON dict.

    Raises:
        ValueError: If no valid JSON could be extracted.
    """
    text = text.strip()

    # Try extracting from ```json ... ``` fence
    if "```json" in text:
        start = text.index("```json") + 7
        end = text.index("```", start)
        text = text[start:end].strip()
    elif "```" in text:
        start = text.index("```") + 3
        if "```" in text[start:]:
            end = text.index("```", start)
            text = text[start:end].strip()

    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try to find first { and last }
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
        return json.loads(text[start:end])
    except (ValueError, json.JSONDecodeError):
        pass

    # Try to find first [ and last ] (for arrays)
    try:
        start = text.index("[")
        end = text.rindex("]") + 1
        return json.loads(text[start:end])
    except (ValueError, json.JSONDecodeError):
        pass

    raise ValueError(f"Could not extract valid JSON from response: {text[:200]}...")


# ── LLM Engine ─────────────────────────────────────────────────────────


class LLMEngine:
    """Cognitive compute engine. Pure reasoning — no state.

    Stateless by design (P0, P1):
    - No stored conversations
    - No identity
    - No memory
    - All context flows in through ContextBuilder

    The engine is the "thinking" layer. It constructs prompts, calls the
    LLM provider, and parses responses into structured outputs.

    Usage:
        engine = LLMEngine(provider, context_builder)
        plan = await engine.plan("Build a web scraper", skills)
    """

    def __init__(
        self,
        provider: LLMProvider,
        context_builder: ContextBuilder,
    ) -> None:
        """Initialize the LLM Engine.

        Args:
            provider: The LLM provider adapter to use.
            context_builder: ContextBuilder for assembling prompt context.
        """
        self._provider = provider
        self._context = context_builder
        logger.info(
            "llm_engine_initialized",
            provider=provider.provider_name,
            default_model=provider.default_model,
        )

    @property
    def active_provider_name(self) -> str:
        """Name of the currently active LLM provider."""
        return self._provider.provider_name

    def switch_provider(self, provider: LLMProvider) -> None:
        """Switch to a different LLM provider at runtime.

        Per P8: Provider switching does not affect state because
        the engine has no state to lose.

        Args:
            provider: The new provider adapter to use.
        """
        old_provider = self._provider.provider_name
        self._provider = provider
        logger.info(
            "llm_engine_provider_switched",
            old_provider=old_provider,
            new_provider=provider.provider_name,
        )

    # ── Core Cognitive Operations ──────────────────────────────────────

    async def think(
        self,
        query: str,
        context: dict[str, Any] | None = None,
    ) -> str:
        """Pure reasoning. Analyze, reason, interpret.

        The most fundamental cognitive operation. Takes a query,
        assembles relevant context, and produces a reasoned response.

        Args:
            query: The question or topic to reason about.
            context: Optional extra context to merge ON TOP of the
                ContextBuilder output. If None, only ContextBuilder
                is used. If provided, its keys are merged into the
                ContextBuilder result (extra context does not replace
                identity/agent_name/etc.).

        Returns:
            The LLM's reasoned response as a string.
        """
        # Always start with ContextBuilder so identity, agent_name,
        # and other required template variables are present.
        base_context = await self._context.build_think_context(query)
        if context:
            base_context.update(context)
        context = base_context

        # Render the system prompt
        system_prompt = _jinja_env.from_string(THINK_SYSTEM_PROMPT).render(**context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": _jinja_env.from_string(THINK_USER_PROMPT).render(query=query)},
        ]

        logger.debug("think_request", query=query[:100])
        try:
            response = await self._provider.complete(messages, temperature=0.7)
            logger.debug("think_response", response_length=len(response))
            return response
        except TokenLimitError:
            logger.warning("think_token_limit", query=query[:100])
            raise
        except ProviderError:
            raise

    async def stream_think(
        self,
        query: str,
        context: dict[str, Any] | None = None,
    ) -> AsyncIterator[str]:
        """Stream reasoning tokens as they are generated.

        Args:
            query: The question or topic to reason about.
            context: Optional pre-built context.

        Yields:
            Tokens of the reasoning response.
        """
        if context is None:
            context = await self._context.build_think_context(query)
        else:
            base = await self._context.build_think_context(query)
            base.update(context)
            context = base

        system_prompt = _jinja_env.from_string(THINK_SYSTEM_PROMPT).render(**context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": _jinja_env.from_string(THINK_USER_PROMPT).render(query=query)},
        ]

        logger.debug("stream_think_request", query=query[:100])
        try:
            async for token in self._provider.complete_stream(messages, temperature=0.7):
                yield token
        except TokenLimitError:
            logger.warning("stream_think_token_limit", query=query[:100])
            raise
        except ProviderError:
            raise

    async def plan(
        self,
        goal: str,
        available_skills: list[dict[str, Any]],
        context: dict[str, Any] | None = None,
    ) -> Plan:
        """Generate an execution plan from a goal and available skills.

        Args:
            goal: The goal to plan for.
            available_skills: List of skill definitions available for use.
            context: Optional pre-built context.

        Returns:
            A structured Plan with ordered steps.

        Raises:
            ProviderError: If the LLM fails to produce a valid plan.
        """
        if context is None:
            context = await self._context.build_plan_context(goal, available_skills)

        system_prompt = _jinja_env.from_string(PLAN_SYSTEM_PROMPT).render(**context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Plan how to achieve this goal: {goal}"},
        ]

        logger.debug("plan_request", goal=goal[:100], skills_count=len(available_skills))
        try:
            response = await self._provider.complete(messages, temperature=0.3)
            data = _extract_json(response)

            steps = []
            for i, step_data in enumerate(data.get("steps", [])):
                steps.append(PlanStep(
                    step_id=str(uuid.uuid4()),
                    action=step_data.get("action", ""),
                    skill_name=step_data.get("skill_name"),
                    parameters=step_data.get("parameters", {}),
                    expected_outcome=step_data.get("expected_outcome", ""),
                ))

            plan = Plan(
                plan_id=str(uuid.uuid4()),
                goal=data.get("goal", goal),
                steps=steps,
                reasoning=data.get("reasoning", ""),
                created_at=datetime.now(UTC),
            )

            logger.info(
                "plan_generated",
                plan_id=plan.plan_id,
                goal=goal[:100],
                step_count=len(steps),
            )
            return plan

        except (ValueError, KeyError) as exc:
            logger.warning(
                "plan_parse_fallback_empty_plan",
                error=str(exc),
                response_preview=response[:200],
                goal=goal[:100],
            )
            # Graceful degradation: return an empty plan instead of raising.
            # The cognitive pipeline continues with think() output as the
            # response — the user still gets a meaningful reply even if
            # the LLM didn't produce structured JSON.
            return Plan(
                plan_id=str(uuid.uuid4()),
                goal=goal,
                steps=[],
                reasoning=f"LLM response was not parseable as JSON; falling back to empty plan. Response preview: {response[:200]}",
                created_at=datetime.now(UTC),
                current_step=0,
            )
        except TokenLimitError:
            raise
        except ProviderError:
            raise

    async def reflect(
        self,
        experience: dict[str, Any],
        identity: dict[str, Any] | None = None,
    ) -> Reflection:
        """Reflect on an experience. Extract lessons, update beliefs.

        Args:
            experience: The experience/episode to reflect on.
            identity: Optional identity data. If None, fetched from context.

        Returns:
            A structured Reflection with lessons and insights.

        Raises:
            ProviderError: If the LLM fails to produce a valid reflection.
        """
        context = await self._context.build_reflect_context(experience)

        # Merge provided identity if given
        if identity:
            context["core_values"] = identity.get("core_values", context.get("core_values", []))
            context["self_description"] = identity.get("self_description", context.get("self_description", ""))
            context["agent_name"] = identity.get("name", context.get("agent_name", "Agent"))

        system_prompt = _jinja_env.from_string(REFLECT_SYSTEM_PROMPT).render(**context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Reflect on this experience: {experience.get('summary', '')}"},
        ]

        logger.debug("reflect_request", experience_summary=experience.get("summary", "")[:100])
        try:
            response = await self._provider.complete(messages, temperature=0.5)
            data = _extract_json(response)

            reflection = Reflection(
                reflection_id=str(uuid.uuid4()),
                summary=data.get("summary", ""),
                lessons_learned=data.get("lessons_learned", []),
                skill_improvement_suggestions=data.get("skill_improvement_suggestions", []),
                identity_implications=data.get("identity_implications", []),
                emotional_tone=data.get("emotional_tone", "neutral"),
            )

            logger.info(
                "reflection_generated",
                reflection_id=reflection.reflection_id,
                lesson_count=len(reflection.lessons_learned),
                emotional_tone=reflection.emotional_tone,
            )
            return reflection

        except (ValueError, KeyError) as exc:
            logger.warning(
                "reflect_parse_fallback_default",
                error=str(exc),
                response_preview=response[:200],
            )
            # Graceful degradation: return a minimal reflection instead
            # of raising. The cognitive pipeline continues and the user
            # still gets the think() output as the response.
            return Reflection(
                reflection_id=str(uuid.uuid4()),
                summary=f"Reflection parsing failed; raw LLM response: {response[:200]}",
                lessons_learned=[],
                skill_improvement_suggestions=[],
                identity_implications=[],
                emotional_tone="neutral",
            )
        except TokenLimitError:
            raise
        except ProviderError:
            raise

    async def compile(
        self,
        experience: dict[str, Any],
        reflection: Reflection,
    ) -> SkillProposal:
        """Compile experience + reflection into a skill proposal.

        Args:
            experience: The original experience.
            reflection: The reflection on that experience.

        Returns:
            A SkillProposal that can be reviewed and stored.

        Raises:
            ProviderError: If the LLM fails to produce a valid proposal.
        """
        context = await self._context.build_compile_context(experience, {
            "summary": reflection.summary,
            "lessons_learned": reflection.lessons_learned,
            "skill_improvement_suggestions": reflection.skill_improvement_suggestions,
            "identity_implications": reflection.identity_implications,
            "emotional_tone": reflection.emotional_tone,
        })

        system_prompt = _jinja_env.from_string(COMPILE_SYSTEM_PROMPT).render(**context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Compile a skill proposal from this experience and reflection."},
        ]

        logger.debug("compile_request", experience_summary=experience.get("summary", "")[:100])
        try:
            response = await self._provider.complete(messages, temperature=0.4)
            data = _extract_json(response)

            proposal = SkillProposal(
                suggested_name=data.get("suggested_name", ""),
                description=data.get("description", ""),
                input_schema=data.get("input_schema", {}),
                output_schema=data.get("output_schema", {}),
                driver_type=data.get("driver_type", "api"),
                action_template=data.get("action_template", {}),
                compiled_from=data.get("compiled_from", []),
                reasoning=data.get("reasoning", ""),
                confidence_estimate=data.get("confidence_estimate", 0.5),
            )

            logger.info(
                "skill_proposal_generated",
                skill_name=proposal.suggested_name,
                driver_type=proposal.driver_type,
                confidence=proposal.confidence_estimate,
            )
            return proposal

        except (ValueError, KeyError) as exc:
            logger.error("compile_parse_error", error=str(exc), response=response[:200])
            raise ProviderError(
                f"Failed to parse skill proposal from LLM response: {exc}",
                code="COMPILE_PARSE_ERROR",
                cause=exc,
            ) from exc
        except TokenLimitError:
            raise
        except ProviderError:
            raise

    # ── Identity Operations ────────────────────────────────────────────

    async def interpret_identity(
        self,
        identity: dict[str, Any],
        context: dict[str, Any],
    ) -> str:
        """Interpret identity for the current context. Produces behavioral guidance.

        Per P3: Identity lives in Memory. The LLM reads it here and produces
        behavioral guidance, but does not modify identity directly.

        Args:
            identity: The agent's identity data.
            context: The current situational context.

        Returns:
            Behavioral guidance text — how the agent should behave now.
        """
        render_context = {
            "agent_name": identity.get("name", "Agent"),
            "identity": identity,
            "context": context,
        }

        system_prompt = _jinja_env.from_string(IDENTITY_INTERPRETATION_PROMPT).render(**render_context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "How should you behave in this context based on your identity?"},
        ]

        logger.debug("interpret_identity_request", agent_name=identity.get("name", "Agent"))
        try:
            response = await self._provider.complete(messages, temperature=0.3)
            logger.debug("interpret_identity_response", response_length=len(response))
            return response
        except TokenLimitError:
            raise
        except ProviderError:
            raise

    async def propose_identity_update(
        self,
        current_identity: dict[str, Any],
        experiences: list[dict[str, Any]],
    ) -> list[IdentityUpdateProposal]:
        """Propose changes to identity based on accumulated experiences.

        Per P3: The LLM proposes; the Memory System decides. This method
        returns proposals, not mutations.

        Args:
            current_identity: The agent's current identity data.
            experiences: Recent experiences that may warrant identity changes.

        Returns:
            A list of IdentityUpdateProposal objects, or empty list if
            no changes are needed.

        Raises:
            ProviderError: If the LLM fails to produce valid proposals.
        """
        render_context = {
            "agent_name": current_identity.get("name", "Agent"),
            "current_identity": current_identity,
            "experiences": experiences,
        }

        system_prompt = _jinja_env.from_string(IDENTITY_UPDATE_PROPOSAL_PROMPT).render(**render_context)

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Review these experiences and propose identity updates if needed."},
        ]

        logger.debug(
            "propose_identity_update_request",
            agent_name=current_identity.get("name", "Agent"),
            experience_count=len(experiences),
        )
        try:
            response = await self._provider.complete(messages, temperature=0.3)
            data = _extract_json(response)

            # Handle both array and object responses
            proposals_data = data if isinstance(data, list) else data.get("proposals", [])
            if not proposals_data:
                return []

            proposals: list[IdentityUpdateProposal] = []
            valid_fields = {f.value for f in IdentityField}

            for item in proposals_data:
                field = item.get("field", "")
                if field not in valid_fields:
                    logger.warning(
                        "identity_update_invalid_field",
                        field=field,
                        valid_fields=list(valid_fields),
                    )
                    continue

                try:
                    proposal = IdentityUpdateProposal(
                        field=IdentityField(field),
                        current_value=item.get("current_value"),
                        proposed_value=item.get("proposed_value"),
                        reasoning=item.get("reasoning", ""),
                        confidence=item.get("confidence", 0.5),
                        experiences_cited=item.get("experiences_cited", []),
                    )
                    proposals.append(proposal)
                except Exception as exc:
                    logger.warning(
                        "identity_update_proposal_invalid",
                        field=field,
                        error=str(exc),
                    )

            logger.info(
                "identity_update_proposals_generated",
                proposal_count=len(proposals),
            )
            return proposals

        except ValueError as exc:
            logger.error("identity_update_parse_error", error=str(exc), response=response[:200])
            raise ProviderError(
                f"Failed to parse identity update proposals: {exc}",
                code="IDENTITY_UPDATE_PARSE_ERROR",
                cause=exc,
            ) from exc
        except TokenLimitError:
            raise
        except ProviderError:
            raise

    # ── Embedding ──────────────────────────────────────────────────────

    async def embed(self, text: str) -> list[float]:
        """Generate an embedding vector for a single text.

        Args:
            text: The text to embed.

        Returns:
            A list of floats representing the embedding vector.
        """
        logger.debug("embed_request", text_length=len(text))
        try:
            embeddings = await self._provider.embed(text)
            return embeddings[0] if embeddings else []
        except ProviderError:
            raise
